name: cauce_mobile
description: "Cauce Mobile - Cliente Flutter para pacientes con SII"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Modelos inmutables
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # HTTP + OpenAPI
  dio: ^5.7.0

  # Auth
  flutter_appauth: ^8.0.1
  flutter_secure_storage: ^9.2.2

  # Persistencia local
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  # Routing
  go_router: ^14.2.7

  # Utilidades
  uuid: ^4.5.0
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Codegen
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  drift_dev: ^2.20.3

  # Testing
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
